maestrano/impac-angular

- src/components/widgets/accounts-comparison/accounts-comparison.directive.coffee
Prevents running comparison mode or loading comparison mode from metadata settings if there aren't two or more organisations available on the widget.
This catches discrepancies between widget.metadata and the potential changes in availability of multiple organisations.
@cesar-tonnoir @ouranos This merge request will fix the widget being unusable in some cases.
On a seperate branch (xaun/rework/accounts-comparison) I have removed the grouping functionality from the front-end and hooked it up to the grouping function I wrote in Impac API. It's working much better, but it is not finished, I need to write some of the front-end behaviour logic outlined here:  https://github.com/maestrano/impac-angular/issues/6
:v:
> Fix for account comparison - single organization

- src/components/widgets-settings/account/account.tmpl.html
- src/components/widgets-settings/accounts-list/accounts-list.directive.coffee
- src/components/widgets-settings/params-checkboxes/params-checkboxes.directive.coffee
- src/components/widgets/accounts-comparison/accounts-comparison.directive.coffee
- src/components/widgets/accounts-comparison/accounts-comparison.tmpl.html
Switching to and from comparison mode now triggers normal metadata update cycle, with api returning formatted accounts data. The params-checkboxes settings directive also now only converts relevant data to metadata.
> Removed grouping functionality from front-end

- src/components/widgets/accounts-comparison/accounts-comparison.directive.coffee
- src/components/widgets/accounts-comparison/accounts-comparison.less
- src/components/widgets/accounts-comparison/accounts-comparison.tmpl.html
- when the returned accounts data is from only one organisation, comparison mode is disabled.
- if comparison mode selection was saved and then returned accounts data is from only one organisation, an error message is displayed and the ability to deselect comparison mode is available. Once deselection is made, the comparison mode is disabled.
> Improved front-end logic for comparable and non-comparable accounts

- src/components/widgets/sales-aged/sales-aged.directive.coffee
- src/components/widgets/sales-comparison/sales-comparison.directive.coffee
- src/components/widgets/sales-growth/sales-growth.directive.coffee
- src/components/widgets/sales-summary/sales-summary.directive.coffee
Fixes integer values displaying as currency across widgets, and prevents having to manually add matchers when extending widget filters to-do with quantity.
@cesar-tonnoir
> string matching logic for quanity selectors across widgets

- bower.json
- src/components/dashboard/dashboard.directive.coffee
- src/components/dashboard/dashboard.less
- src/components/dashboard/dashboard.tmpl.html
- src/services/main/main.svc.coffee
- workspace/index.html
- workspace/index.js
- added toastr bower dep for alerts
- toastr alerts for errors requiring api credentials & loading organizations
- workspace errors now properly reject promises to stop endless load
- new dashboard.tmpl.html screen for displayed failed dhb load message
- hides dashboards controls which would otherwise still be visible.
@cesar-tonnoir please review
> feat: workspace cred's alert & dhb load fail handling

- src/services/kpis/kpis.svc.coffee
Fixes the issue where pusher alerts where only registered on app refresh or
direct alerts modal add or remove.
@cesar-tonnoir
> Fix: not registering pusher alerts on kpi#update and kpi#delete

- src/components/kpi/kpi.less
- src/components/kpis-bar/kpis-bar.directive.coffee
- src/components/kpis-bar/kpis-bar.less
- src/components/kpis-bar/kpis-bar.tmpl.html
@xaun can you please review?
Status update - still a few things to fix:
- remove account name from kpi attached to widget
- discovery endpoint wasn't working on mine?..
- saving the kpis when on edit mode is not obvious
- alerting modal should take all the watchables into account
- API to return dynamic edit captions
- API to return appropriate emphasis for all the existing kpis
- kpis bar's `kpisEditSettings` is buggy: settings are not removed when the kpi is removed from `$scope.kpis` -> couldn't the edit settings be saved in the kpi object (in $scope.kpis)
- bug spotted (not appearing 100% of the time): when I try to attach a kpi "too fast", I receive a 400 because the element_watched cannot be blank. Probably a problem with the ng-init: we should attach the element_watched to the …
> [IMPAC-175] [IMPAC-286] Kpis selector

- gulp/build.js
- gulp/scripts.js
- package.json
I added a header for both impac-angular.js and impac-angular.min.js files produced by gulp giving some details about the module (version, name, license...). This is taken from the bower.json file.
Also added a clumsy version module that can be called from the console.
`impac.version`
returning whatever version number is in the bower.json file
`1.3.9`
**Bug:** In order to work, the page needs to be refreshed at least once before the above command works.
> [IMPAC - 307] - Added an automatic version generator

- src/components/dashboard/dashboard.directive.coffee
- src/services/dashboards/dashboards.spec.js
- src/services/dashboards/dashboards.svc.coffee
This exposes the ability for parent applications to trigger a dashboard spinner
loader (e.g mnoe-demo on organization selection). This improves the transition by
hiding the doms re-binding of the widget ng-repeat choppyness.
@alexnoox @cesar-tonnoir please review
> Adds a dhb.svc callback for triggered dhb loader spinner

- README.md
- bower.json
- src/components/widgets-common/data-not-found/data-not-found.directive.coffee
- src/services/assets/assets.svc.coffee
- workspace/index.js
Assets in bower_componets are not publically accessible by the browser.
The parent app must add a gulp task to abstract all the relevant bower_components
assets and build them into a dist/ or public/ folder. Impac Angular need to be
provided with this default images path.
> Fix image paths for default images

- Changelog.md
- src/components/widgets/sales-new-vs-existing-customers/sales-new-vs-existing-customers.directive.coffee
@cesar-tonnoir Is it correct to represent negative values on a pie graph like this? I've seen it being done on other widgets across the app (e.g assets summary), so I thought I would stick to it and just fix the percentage calculation for the tooltip. 
Maybe we should consider using the Polar Area chart (not yet integrated with impac-angular): http://www.chartjs.org/docs/#polar-area-chart-introduction
End result:
> [IMPAC-262] Fix incorrect tooltip values

- Changelog.md
- src/components/widgets/sales-opportunities-funnel/sales-opportunities-funnel.directive.coffee
@cesar-tonnoir this fixes an issue i discovered when you deselect an assignee, then delete all your opportunities, refresh the widget so there is "no data found", then add an opp of the previously deselected assignee, the widget would show nothing. Note this is similar, but a different issue to what was raised on JIRA IMPAC-397. 
The fix for 397 is in the Impac! PR: https://github.com/maestrano/impac/pull/444
> [IMPAC-397] Enforce at least 1 opp-funnel option selection

- Changelog.md
- src/services/kpis/kpis.svc.coffee
- src/services/widgets/widgets.svc.coffee
@cesar-tonnoir while working on IMPAC-515 (PR: https://github.com/maestrano/impac/pull/455), I noticed on sync-apps complete, two `/get_widget` requests were being made for each widget. One request for `ImpacWidgetsSvc.refreshAll` and second request because of `ImpacKpisSvc.refreshAll`.
This is because `ImpacDashboardsSvc.load` causes the widgets models to be re-set, and consequently, `.show` to be run for each of them. I don't believe the `ImpacKpisService.load` method's force param should also force the userData & dashboard reload.
> Fix refreshAll kpis wrongly forcing a dashboard reload

- Changelog.md
- README.md
@cesar-tonnoir I improved the providers section documenting all options, and organising it in a more linkable way, for something I hope enterprise could be directed to. Let me know what you think. 
Take a look at the formatted result here: https://github.com/xaun/impac-angular/blob/improv-readme/README.md#configuration--customisation
> Add improved config / customise section to readme

- Changelog.md
- README.md
- src/components/dashboard/dashboard.directive.coffee
- src/components/dashboard/dashboard.less
- src/components/dashboard/dashboard.tmpl.html
- src/stylesheets/variables.less
The main advantage is row columns will always be the same height, with a configurable min-height. 
Note: a Flexbox limitation is when a column's context wraps (e.g widget name), pushing beyond the minimum height, the columns on **that row** will match the height. But the columns on the previous/following wrapped rows will not ([See link here](http://stackoverflow.com/questions/36004926/is-it-possible-to-have-equal-height-columns-in-a-multi-line-flex-container)).
On the screenshot below, the screen size is reduce so some of the widget names are wrapping. The rows with at least one column with a wrapped widget name, are then all larger to accommodate this. As you may see, the last row's columns are smaller. This is apart of the limitation noted above. I still think this is a big win, and …
> Improve widget selector using a Flexbox grid

- gulp/watch.js
@cesar-tonnoir improves cpu perf by ~30% running serve. Also removed the bower_components watch as it's pretty unnecessary to be watching all those files just so when a component is bower installed it reloads; can just re-run the task on that case. 
:beers:
> Add gulp interval improving CPU perf

- Changelog.md
- src/components/widgets/hr-salaries-summary/hr-salaries-summary.directive.coffee
- src/components/widgets/hr-workforce-summary/hr-workforce-summary.directive.coffee
- src/components/widgets/sales-aged/sales-aged.directive.coffee
- src/components/widgets/sales-list/sales-list.directive.coffee
- src/components/widgets/sales-margin/sales-margin.directive.coffee
- src/components/widgets/sales-segmented-turnover/sales-segmented-turnover.directive.coffee
- src/components/widgets/sales-summary/sales-summary.directive.coffee
Fixes some widgets breaking during load because w.initContext is not designed for async definitions (i18n async translations were being made).
> [IMPAC-592] use instant translations during w.initContext

- Changelog.md
- src/components/widgets/sales-customer-details/sales-customer-details.tmpl.html
@cesar-tonnoir this code was removed by https://github.com/maestrano/impac-angular/commit/a58322c2b45955a40c8b08a89b54fa5b9bf3f999, but it is being used in the template to access the customer fields. Was there a reason for this or was it a mistake? This is working well now on my dev, and I can't seem to see why it would be removed. Please review thanks.
> [IMPAC-637] Fix customer details fields always empty

- Changelog.md
- gulp/server.js
- src/impac-angular.module.js
- src/impac-angular.run.coffee
- Add dependency to xeditable so widgets titles can be edited without configuration in host apps
- Serve glyphicons in workspace
> [IMPAC-658] Fix dependency to xeditable

- src/components/widgets/accounts-comparison/accounts-comparison.directive.coffee
- src/components/widgets/accounts-comparison/accounts-comparison.less
- src/components/widgets/accounts-comparison/accounts-comparison.tmpl.html
@xaun @cesar-tonnoir 
Fixes include: 
-Chart updates asynchronously when 1st account added
-Chart legend items don't extend out of widget when multiple added
-Purple account button not blank on refresh
> [IMPAC-649] Account comparison widget bugs

- bower.json
- src/components/widgets-common/chart-threshold/chart-threshold.component.coffee
- src/components/widgets-common/chart-threshold/chart-threshold.less
- src/components/widgets-common/chart-threshold/chart-threshold.tmpl.html
- src/components/widgets-settings/dates-picker/dates-picker.directive.coffee
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.directive.coffee
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.less
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.tmpl.html
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.less
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
- src/services/highcharts-factory/highcharts-factory.svc.coffee
- Uses highstock instead of highchart
- Build labels based on timestamps returned with each series instead of dates strings
- Better zooming capabilities
- Change time period using dates pickers
- Better granularity (use daily intervals)
Goes with https://github.com/maestrano/impac-finance-bolt/pull/44
**TODO**
> [IMPAC-618] Better time management for cashflow widgets

- bower.json
- src/components/common/transactions-list/transactions-list.component.coffee
- src/components/common/transactions-list/transactions-list.less
- src/components/common/transactions-list/transactions-list.tmpl.html
- src/components/widget/widget.less
- src/components/widget/widget.tmpl.html
- src/components/widgets-common/chart-threshold/chart-threshold.component.coffee
- src/components/widgets-common/chart-threshold/chart-threshold.less
- src/components/widgets-settings/dates-picker/dates-picker.directive.coffee
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.directive.coffee
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.less
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.tmpl.html
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.less
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
- src/impac-angular.module.js
- src/services/bolt-resources/bolt-resources.svc.coffee
- src/services/highcharts-factory/highcharts-factory.svc.coffee
- src/stylesheets/globals.less
**Note** check only changes from #fda28a3 as feature/cash-trx-list branches off feature/time-management which is not merged yet
- New BoltResources service to query the Bolt's json api
- New component to display transactions list with pagination
- Displays transactions details when the user clicks on a bar (shows bills when click on "Payables", invoices when click on "Receivables")
@alexnoox feel free to have a look if you wish ;)
**Dependencies**
- https://github.com/maestrano/impac/pull/497
- https://github.com/maestrano/impac-finance-bolt/pull/45
> [IMPAC-617] Transactions list in Cash Projection widget

- src/components/widgets-common/chart-threshold/chart-threshold.component.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/services/highcharts-factory/highcharts-factory.svc.coffee
@cesar-tonnoir please review this refactor for the thresholds. Note this is excluding the threshold tooltips as I am experiencing problems with this and stock charts, but wanted to get at least this refactor finished today.
This refactor is linked to your comments made here: https://github.com/maestrano/impac-angular/pull/393
> [IMPAC-666] Refactor thresholds

- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
@cesar-tonnoir @xaun 
Clicking on one of these legend items should activate / deactivate the whole series.
https://maestrano.atlassian.net/browse/IMPAC-669
> [IMPAC-669] Fuse cash projection and cash flow legend icons

- src/components/widgets/accounts-cash-balance/accounts-cash-balance.directive.coffee
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.tmpl.html
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
- src/services/highcharts-factory/highcharts-factory.svc.coffee
After this change, the user won't be able to modify the time period on the cashflow widgets, but only to change the zooming instead.
Depends on https://github.com/maestrano/impac-finance-bolt/pull/51
> [IMPAC-667] Update time management on cashflow widgets

- Changelog.md
- src/components/dashboard/dashboard.less
@cesar-tonnoir @xaun This PR changes the overflow attr for the widget selector to auto. This is so that the scrollbar doesn't appear anymore on IE11 as it makes it seem as if the selector is too long and overflowing out of the menu. Will leave additional comments on JIRA as I cannot link the ticket here directly. Please review. :)
> [BUG] Change overflow attr to auto

- src/components/widgets-common/chart-threshold/chart-threshold.component.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/services/highcharts-factory/highcharts-factory.svc.coffee
Some things to note:
- `Highcharts.addEvent(chart.hc.container, 'click', onChartClick)` applies the click event to the whole canvas, causing the need for the existing (incomplete) guarding in the `onChartClick` callback method. 
- The native `chart.events.click` callback only triggers on chart clicks. Fixing the problem of needing to guard for things like legend, zoom bar, etc clicks.
- The native `chart.events.click` callback can not be updated after render.
> [IMPAC-663] Fix unwanted triggering of create threshold panel

- src/components/dashboard-settings/sync-apps/sync-apps.directive.js.coffee
- src/components/dashboard-settings/sync-apps/sync-apps.tmpl.html
- src/locales/en-AU.json
Only displays 'Sync in real time' when there are cube apps running.
When no apps (at all) are running, displays 'No apps are running!'
/!\ Relies on a new Organization method on the hub, relayed by mno-enterprise.
https://github.com/maestrano/maestrano-hub/pull/802
https://github.com/maestrano/mno-enterprise/pull/567
> [IMPAC-665] Sync status on dashboard

- src/components/widgets/accounts-cash-balance/accounts-cash-balance.less
Add max-height to allow overflow scroll to work.
> [IMPAC-759] Fix cash_balance accounts list

- src/components/widgets-settings/tag-filter/tag-filter.directive.coffee
Adds ASCII encode/decoding for tag values. 
I looked at implementing some parsing on the params level in the widgets service. But I couldn't find something that worked perfectly for both not effecting other features & parsing it to the right ASCII format where the API would work and filter the accounts. Also as the app is not specced very well, I would rather parse the tag values in the isolated component, so we don't have to do extensive testing across everything incase the blanket parsing causes some regressions on other things.
> [IMPAC-681] Fix tags to allow special chars

- src/components/widgets-settings/organizations/organizations.directive.coffee
- src/components/widgets-settings/organizations/organizations.less
- src/components/widgets-settings/organizations/organizations.tmpl.html
Radio mode can be set on Widgets by adding parameter `organization-mode="'single'" ` to `setting-organizations` directive.
> [IMPAC-757] Added radio mode for organization

- src/components/widgets/accounts-ratios/accounts-ratios.directive.coffee
- src/components/widgets/accounts-ratios/accounts-ratios.tmpl.html
Reverts maestrano/impac-angular#472
@MAhsenArif
> Revert "IMPAC-758] Date hidden in X-axis for current ratio and debt service widget"

- src/components/widgets-settings/organizations/organizations.directive.coffee
- src/components/widgets/accounts-assets-liability-summary/accounts-assets-liability-summary.tmpl.html
- src/components/widgets/accounts-assets-summary/accounts-assets-summary.tmpl.html
- src/components/widgets/accounts-assets-vs-liabilities/accounts-assets-vs-liabilities.tmpl.html
- src/components/widgets/accounts-balance-sheet/accounts-balance-sheet.directive.coffee
- src/components/widgets/accounts-class-comparison/accounts-class-comparison.tmpl.html
- src/components/widgets/accounts-detailed-classifications/accounts-detailed-classifications.tmpl.html
- src/components/widgets/accounts-expense-weight/accounts-expense-weight.tmpl.html
- src/components/widgets/invoices-list/invoices-list.accessible.tmpl.html
- src/components/widgets/invoices-list/invoices-list.tmpl.html
- src/components/widgets/sales-leads-list/sales-leads-list.directive.coffee
- src/components/widgets/sales-leads-list/sales-leads-list.tmpl.html
- src/services/dashboards/dashboards.svc.coffee
- src/services/linking/linking.svc.coffee
@cesar-tonnoir 
I was able to order the settings internally in the directives -- however, the widget-specific data was not uniform enough to do this at the directive level. Since lots of widgets reuse the same html file, I did not have to add that many orderBys.
> [IMPAC-751] Fixed Multi-Company Ordering

- src/components/chart/chart.directive.coffee
- src/components/widgets-common/chart-threshold/chart-threshold.component.coffee
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/components/widgets/accounts-class-comparison/accounts-class-comparison.directive.coffee
- src/services/highcharts-factory/highcharts-factory.svc.coffee
@xaun
Implemented what we discussed. Its a pretty big pull request, so let me know if you have any questions. Let me know when you want me to squash ( would rather squash when ready to merge, as keeping track of my commits helps me).
I think this is an improvement over what was there originally. Only thing is its a bit confusing when @options should be populated in constructor vs in setter. All the dynamic options under the template, I put into setter methods, because they seemed specific to line charts.
> [IMPAC-745] Fix Cash Projection Crash and Refactor Highcharts

- src/components/common/transactions-list/transactions-list.less
- src/components/common/transactions-list/transactions-list.tmpl.html
- fixes revert date bug by using flex 
- fixes transactions list not 100% widget width < screen md size
- fixes pagination & money in / out buttons wrapping and overlapping list on smaller screen sizes
> [IMPAC-848] Transactions list display bugs

- src/components/widgets-common/chart-threshold/chart-threshold.less
Fixes elements wrapping, and no need for it to be so wide.
Before
After
> [IMPAC-668] Smaller chart-threshold amount input

- src/components/common/trends-add/trends-add.component.coffee
- src/components/common/trends-add/trends-add.tmpl.html
- src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/services/bolt-resources/bolt-resources.svc.coffee
- For the method createUser, we need the firstCompanyId, which may not have been fetched before
- When requesting an index on the bolt, the params were decoded.
As a result, "emmanuel+1@maestrano.com" would be sent as is in the request params, the '+' not being encoded making the request fail
> Do not decode paramsHash for bolt requests
