maestrano/impac-angular

- src/components/widgets-common/editable-title/editable-title.less
- src/components/widgets-common/editable-title/editable-title.tmpl.html
- src/components/widgets/invoices-list/invoices-list.tmpl.html
- src/stylesheets/globals.less
Reverts maestrano/impac-angular#63
@alexnoox, can you plz:
- check layout on mno (see screenshot)
- make sure the text can be selected using the mouse (so far it is dragging the whole widget)
thx!
> Revert "Bugfix/frontend"

- src/components/kpi/kpi.directive.coffee
- src/components/kpi/kpi.less
- src/components/kpi/kpi.tmpl.html
- src/components/kpis-bar/kpis-bar.directive.coffee
- src/components/kpis-bar/kpis-bar.less
- src/components/kpis-bar/kpis-bar.tmpl.html
- src/components/widgets-common/editable-title/editable-title.less
> KPI layout and behaviour fixes

- src/components/kpi/kpi.directive.coffee
- src/components/kpi/kpi.less
- src/components/kpi/kpi.tmpl.html
- src/components/kpis-bar/kpis-bar.directive.coffee
- src/components/kpis-bar/kpis-bar.less
- src/components/kpis-bar/kpis-bar.tmpl.html
- src/components/widgets-common/editable-title/editable-title.less
Reverts maestrano/impac-angular#69
> Revert "KPI layout and behaviour fixes"

- src/components/widgets/invoices-aged-payables-receivables/invoices-aged-payables-receivables.tmpl.html
> changed label for total values in aged payables receivables widget

- src/components/widgets/invoices-aged-payables-receivables/invoices-aged-payables-receivables.less
- src/components/widgets/invoices-aged-payables-receivables/invoices-aged-payables-receivables.tmpl.html
> Aged payables receivables/asterisk message

- Changelog.md
- src/filters/mno-currency.js.coffee
> improvements to mno-currency

- Changelog.md
@cesar-tonnoir thought I'de quickly add this
> Added new widget (New vs Existing Customers) to Changelog.md

- src/components/widgets/invoices-list/invoices-list.directive.coffee
@cesar-tonnoir for when ever you feel like rebuilding - here is currency displayed in tooltips.
> add currency to invoice list tooltip

- gulp/build.js
> add ngAnnotate to dist/impac-angular.js

- src/components/widgets/sales-new-vs-existing-customers/sales-new-vs-existing-customers.directive.coffee
- src/components/widgets/sales-new-vs-existing-customers/sales-new-vs-existing-customers.less
- src/components/widgets/sales-new-vs-existing-customers/sales-new-vs-existing-customers.spec.js
- src/components/widgets/sales-new-vs-existing-customers/sales-new-vs-existing-customers.tmpl.html
- src/impac-angular.module.js
- changed name of component from new-vs-old-customers to new-vs-existing-customers
- updated spec, & improve spec for w.format method
@cesar-tonnoir please review
> updates: new-vs-existing-customers widget

- DEVELOPER.md
updates to how to create a widget, excluding step 1 (widget templates)
@cesar-tonnoir
> update: [IMPAC-131] developer.md

- gulp/build.js
- gulp/scripts.js
> fix: remove sourcemaps from scripts & build task

- Changelog.md
- src/services/kpis/kpis.svc.coffee
- workspace/index.js
@cesar-tonnoir please review :beers:
> Feat/http interceptor [IMPAC-141]

- src/components/dashboard/dashboard.directive.coffee
Reverts maestrano/impac-angular#166
> Revert "Fix - UI Sortable"

- Changelog.md
- bower.json
- package.json
- src/components/dashboard/dashboard.directive.coffee
> Release 1.3.1 (Week 17)

- src/components/widgets/accounts-profit-and-loss/accounts-profit-and-loss.tmpl.html
- src/components/widgets/hr-payroll-summary/hr-payroll-summary.tmpl.html
- src/components/widgets/invoices-aged-payables-receivables/invoices-aged-payables-receivables.tmpl.html
- src/components/widgets/sales-comparison/sales-comparison.tmpl.html
- src/components/widgets/sales-performance/sales-performance.tmpl.html
> [IMPAC-233] add track by to suspicious ng-repeat expressions

- karma-min.conf.js
- karma.conf.js
- src/components/dashboard-settings/currency/currency.spec.js
- src/components/kpi/kpi.less
- src/components/kpi/kpi.tmpl.html
- src/components/widgets-settings/attach-alerts/attach-kpis.directive.coffee
- src/components/widgets-settings/attach-alerts/attach-kpis.less
- src/components/widgets-settings/attach-alerts/attach-kpis.tmpl.html
- src/stylesheets/globals.less
- src/stylesheets/variables.less
@cesar-tonnoir fixes for [IMPAC-284]
> Fix display issues for kpis & widget kpis

- src/components/widgets-settings/dates-picker/dates-picker.directive.coffee
- src/components/widgets/sales-summary/sales-summary.directive.coffee
@ouranos Please review and merge
> Fix apply button when date range changes

- src/components/widgets-settings/time-presets/time-presets.directive.coffee
Fix autoselection when from/to are functions and not values
> Fix Date Preset auto-selection

- workspace/index.js
Added an optional field in the settings to specify the organisation to select by default.
> Add org-uid in workspace settings

- src/components/widgets-common/info-panel/info-panel.less
Fixed a little bug with the info-pannel.
The issue was that when a user clicked the setting button and then the info button, the info was partially hidden by the settings.
E.g: Account Balance widget.
> Fixed a little bug with the info-pannel

- src/components/kpis-bar/kpis-bar.tmpl.html
Fixed the issue with the drag and drop on KPIs not working.
> [IMPAC-303] - KPI FE - Drag & drop now working

- Changelog.md
- src/components/kpi/kpi.directive.coffee
- src/components/kpi/kpi.less
- src/components/kpi/kpi.tmpl.html
- src/components/kpis-bar/kpis-bar.directive.coffee
- src/components/kpis-bar/kpis-bar.less
- src/components/kpis-bar/kpis-bar.tmpl.html
- src/components/widgets-settings/attach-kpis/attach-kpis.tmpl.html
- src/components/widgets-settings/dates-picker/dates-picker.directive.coffee
- src/components/widgets/accounts-balance/accounts-balance.directive.coffee
- src/components/widgets/accounts-balance/accounts-balance.tmpl.html
- src/impac-angular.constant.coffee
- src/services/kpis/kpis.svc.coffee
- src/services/widgets/widgets.svc.coffee
- src/stylesheets/variables.less
@cesar-tonnoir @alexnoox if you guys could review this PR by Monday arvo next week that would be sweet. Especially the "Dates picker for KPIs bar" commit. 
Cheers :beers:
> Kpis consolidation

- src/components/kpi/kpi.directive.coffee
- src/components/kpi/kpi.less
- src/components/kpi/kpi.tmpl.html
- src/components/kpis-bar/kpis-bar.directive.coffee
- src/components/kpis-bar/kpis-bar.less
- src/components/kpis-bar/kpis-bar.tmpl.html
- src/impac-angular.constant.coffee
- src/services/kpis/kpis.svc.coffee
- src/stylesheets/variables.less
@cesar-tonnoir could you please review for me. :beers:
> Kpis fixes

- workspace/index.js
@cesar-tonnoir please review
Also, should the `mno_url` be updated to `https://get-uat.maestrano.io` ?
> Fixes for workspace and kpis & alerting API changes compatibility

- Changelog.md
- src/components/dashboard-settings/sync-apps/sync-apps.directive.js.coffee
- src/services/linking/linking.svc.coffee
> Fix sync statuses modal display

- Changelog.md
- src/components/alerts-config/alerts-config.modal.html
- src/components/dashboard/dashboard.directive.coffee
- src/components/dashboard/dashboard.less
> [IMPAC-380] Hide widgets selector on dashboard deletion

- src/services/routes/routes.svc.coffee
- workspace/app/services/dev-settings.svc.js
> Refactor routes service & update workspace config

- src/components/dashboard-settings/pdf-mode/pdf-mode.tmpl.html
> [MPAC-394] Add Tooltips for Dashboard action Print pdf

- src/components/dashboard-settings/sync-apps/sync-apps.directive.js.coffee
- src/components/dashboard-settings/sync-apps/sync-apps.tmpl.html
- src/components/widgets/sales-leads-funnel/sales-leads-funnel.tmpl.html
- src/components/widgets/sales-leads-list/sales-leads-list.tmpl.html
> Angular Upgrade Fixes

- bower.json
@xaun @cesar-tonnoir 
Guys, I updated those libs as they are easy to test to see if there is any problems, and also to be coherent with the versions in `mno-enterprise-angular`.
> Upgrade ui-sortable and xeditable versions

- Changelog.md
- src/components/dashboard-selector/dashboard-selector.directive.coffee
- src/components/kpis-bar/kpis-bar.directive.coffee
- src/impac-angular.constant.coffee
> [IMPAC-421] Fix kpis bar dates picker initialization

- Changelog.md
- src/components/dashboard-selector/dashboard-selector.directive.coffee
- src/components/kpis-bar/kpis-bar.directive.coffee
- src/impac-angular.constant.coffee
Reverts maestrano/impac-angular#283
> Revert "[IMPAC-421] Fix kpis bar dates picker initialization"

- src/components/kpi/kpi.directive.coffee
- src/components/kpi/kpi.tmpl.html
> [IMPAC-338] Fix kpi do not update extra param

- src/components/dashboard-settings/sync-apps/sync-apps.directive.js.coffee
- src/components/kpi/kpi.directive.coffee
- src/services/kpis/kpis.svc.coffee
@cesar-tonnoir please review
Small change needed on MNOE to allow opts params through in the proxied #index route: https://github.com/maestrano/mno-enterprise/pull/226
> [IMPAC-328] refresh KPIs after first sync

- Changelog.md
- src/components/widgets/accounts-cash-summary/accounts-cash-summary.directive.coffee
- src/components/widgets/accounts-profit-and-loss/accounts-profit-and-loss.directive.coffee
- src/components/widgets/hr-payroll-summary/hr-payroll-summary.directive.coffee
- src/components/widgets/invoices-aged-payables-receivables/invoices-aged-payables-receivables.directive.coffee
- src/components/widgets/sales-comparison/sales-comparison.directive.coffee
- src/components/widgets/sales-performance/sales-performance.directive.coffee
See description on PR for release/1.5.0-rc4: https://github.com/maestrano/impac-angular/pull/307
> Fix/485 drill down params for v1.4.8

- src/components/widgets-common/currency-conversions/currency-conversions.less
- src/components/widgets-common/currency-conversions/currency-conversions.tmpl.html
- src/components/widgets/hr-employee-details/hr-employee-details.less
- src/components/widgets/invoices-list/invoices-list.directive.coffee
- src/components/widgets/invoices-list/invoices-list.less
- src/components/widgets/invoices-list/invoices-list.tmpl.html
- src/components/widgets/sales-comparison/sales-comparison.directive.coffee
- src/components/widgets/sales-comparison/sales-comparison.less
- src/components/widgets/sales-comparison/sales-comparison.tmpl.html
- src/components/widgets/sales-customer-details/sales-customer-details.directive.coffee
- src/components/widgets/sales-customer-details/sales-customer-details.less
- src/components/widgets/sales-customer-details/sales-customer-details.tmpl.html
- src/components/widgets/sales-list/sales-list.directive.coffee
- src/components/widgets/sales-list/sales-list.less
- src/components/widgets/sales-list/sales-list.tmpl.html
- src/components/widgets/sales-top-customers/sales-top-customers.directive.coffee
- src/components/widgets/sales-top-customers/sales-top-customers.less
- src/components/widgets/sales-top-customers/sales-top-customers.tmpl.html
- src/stylesheets/globals.less
- Added currency info to invoices list widget
> [IMPAC-534] Add currency info to sales widgets

- src/components/widget/widget.less
- src/components/widgets-common/editable-title/editable-title.less
- src/components/widgets-common/editable-title/editable-title.tmpl.html
- src/components/widgets/accounts-balance-sheet/accounts-balance-sheet.less
- src/components/widgets/sales-customer-details/sales-customer-details.directive.coffee
- src/components/widgets/sales-segmented-turnover/sales-segmented-turnover.less
- src/components/widgets/sales-segmented-turnover/sales-segmented-turnover.tmpl.html
Fixes several CSS glitches + bug on customer selection (customer details)
@xaun I'll merge that to be able to build / deploy / test that today. Can you please review after I've merged?
> Fix css glitches

- Changelog.md
- src/services/utilities/utilities.svc.coffee
Note, singular reads better as "Show last year", rather than "Show last 1 year".
> [IMPAC-448] Fix period hidden in "show last month"

- Changelog.md
- src/components/dashboard-selector/dropdown.tmpl.html
- src/components/dashboard/dashboard.directive.coffee
- src/components/dashboard/dashboard.less
- src/components/dashboard/dashboard.tmpl.html
- src/stylesheets/globals.less
- Fixes misalignment of widget-item text to icons shown in the JIRA screenshot
- Fixes the widget selector container exceeding mobile viewport
- Fixes close selector button not visible on mobile screens
> [IMPAC-545] Fix css responsivenes for widgets selector

- Changelog.md
- src/components/widgets/accounts-custom-calculation/accounts-custom-calculation.directive.coffee
@cesar-tonnoir I thought it should also apply the dates range on "save"
> Custom calc settings

- src/stylesheets/variables.less
Tag not urgent - to be tagged with other fixes
> Set default row min height to 0px (widget selector)

- src/components/widgets-settings/offsets/offsets.directive.coffee
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.directive.coffee
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.less
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.tmpl.html
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.less
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
> Bolt widgets - Simulation mode

- src/components/widgets/accounts-accounting-values/accounts-accounting-values.tmpl.html
> fix broken multi-currency on EBITDA

- src/components/widgets-common/chart-threshold/chart-threshold.component.coffee
- src/components/widgets-common/chart-threshold/chart-threshold.less
- src/components/widgets-common/chart-threshold/chart-threshold.tmpl.html
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/services/highcharts-factory/highcharts-factory.svc.coffee
- src/services/kpis/kpis.svc.coffee
> IMPAC-598 threshold improv

- src/impac-angular.module.js
- src/services/currency-rates/currency-rates.svc.coffee
> [IMPAC-506] - Added currency-rates service

- Changelog.md
- src/components/widgets/accounts-assets-liability-summary/accounts-assets-liability-summary.tmpl.html
- src/components/widgets/accounts-assets-summary/accounts-assets-summary.tmpl.html
- src/components/widgets/accounts-assets-vs-liabilities/accounts-assets-vs-liabilities.tmpl.html
- src/components/widgets/accounts-cash-summary/accounts-cash-summary.tmpl.html
- src/components/widgets/accounts-class-comparison/accounts-class-comparison.tmpl.html
- src/components/widgets/accounts-comparison/accounts-comparison.tmpl.html
- src/components/widgets/accounts-profit-and-loss/accounts-profit-and-loss.tmpl.html
- src/components/widgets/hr-payroll-summary/hr-payroll-summary.tmpl.html
- src/components/widgets/hr-salaries-summary/hr-salaries-summary.tmpl.html
- src/components/widgets/hr-workforce-summary/hr-workforce-summary.tmpl.html
- src/components/widgets/invoices-aged-payables-receivables/invoices-aged-payables-receivables.tmpl.html
- src/components/widgets/sales-comparison/sales-comparison.tmpl.html
- src/components/widgets/sales-performance/sales-performance.tmpl.html
- src/components/widgets/sales-segmented-turnover/sales-segmented-turnover.tmpl.html
IE does not like angular expressions in html attributes like style. @ouranos
> [IMPAC-631] use ngStyle when binding values

- src/components/widgets/hr-employees-list/hr-employees-list.directive.coffee
Adds yearly period option & use instant translations.
> [IMPAC-638] Improve employees list period options

- Changelog.md
- src/components/widgets/hr-payroll-summary/hr-payroll-summary.directive.coffee
- src/components/widgets/hr-payroll-summary/hr-payroll-summary.tmpl.html
@cesar-tonnoir this but has been in the codebase since 2015-10-13 😂
> [IMPAC-634] Fix payroll summary chart not rendering

- Changelog.md
- README.md
- src/locales/en-AU.json
- src/locales/zh-HK.json
- Remove dataNotFound assets from readme.md
- Add new dataNotFound theming configuration to readme.md
- Update Changelog to descripe config change locations
- Remove unused locale
@cesar-tonnoir please review & merge these - sorry I missed them in the PR review.
> Cleanups for demo-data PR

- src/components/widget/widget.less
- src/components/widget/widget.tmpl.html
- src/components/widgets/accounts-expense-weight/accounts-expense-weight.less
- src/stylesheets/globals.less
> [IMPAC-650] Fix Widgets overlapping content

- src/components/widgets-common/chart-threshold/chart-threshold.component.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/services/highcharts-factory/highcharts-factory.svc.coffee
Reviewed on this PR: https://github.com/maestrano/impac-angular/pull/407
> Refactor threshold

- src/components/common/transactions-list/transactions-list.component.coffee
- src/components/common/transactions-list/transactions-list.tmpl.html
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
- src/services/bolt-resources/bolt-resources.svc.coffee
- src/services/highcharts-factory/highcharts-factory.svc.coffee
- Filter transactions on expected payment date instead of due date
- Update expected payment date for each transaction
- Fix timezone-related errors
> [IMPAC-614] Add editable expected payment date to transactions list

- Changelog.md
- bower.json
- package.json
- src/components/common/transactions-list/transactions-list.component.coffee
- src/components/common/transactions-list/transactions-list.less
- src/components/common/transactions-list/transactions-list.tmpl.html
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/services/highcharts-factory/highcharts-factory.svc.coffee
- src/services/kpis/kpis.svc.coffee
- src/services/widgets/widgets.svc.coffee
- Better handling of timestamps returned by the backend (taking timezone into account)
- Remember zooming on chart (update of metadata)
> Better timezones handling

- Changelog.md
- bower.json
- package.json
- src/components/widgets/accounts-cash-balance/accounts-cash-balance.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- Add timeout to zooming option persistence to avoid flooding Mnohub with PUT requests
> Fix - Persisting zooming options

- src/components/widgets/sales-customer-engagement/sales-customer-engagement.directive.coffee
- src/components/widgets/sales-customer-engagement/sales-customer-engagement.less
- src/components/widgets/sales-customer-engagement/sales-customer-engagement.tmpl.html
- src/impac-angular.module.js
- select offer with param-selector
- render Stockchart
> Add sales-customer-engagement widget

- src/components/widgets-settings/last-time-period/last-time-period.directive.coffee
- src/components/widgets-settings/last-time-period/last-time-period.less
- src/components/widgets-settings/last-time-period/last-time-period.tmpl.html
- src/components/widgets/sales-offer-performance/sales-offer-performance.directive.coffee
- src/components/widgets/sales-offer-performance/sales-offer-performance.less
- src/components/widgets/sales-offer-performance/sales-offer-performance.tmpl.html
- src/impac-angular.module.js
> Update offer performance widget

- Changelog.md
- bower.json
- package.json
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
Enables the transactions stacking provided by the Bolt with minimum impact on the front-end.
Goes with https://github.com/maestrano/impac-finance-bolt/pull/65
> [IMPAC-616] Stack invoices and Bills

- src/filters/moment-date.filter.coffee
I am unable to assign reviewers.
@cesar-tonnoir @ouranos 
Refactor with lodash for ie11
this fixes both:
https://maestrano.atlassian.net/browse/IMPAC-727
https://maestrano.atlassian.net/browse/IMPAC-728
> [IMPAC-728] Refactor using lodash for ie11

- Changelog.md
- bower.json
- package.json
- src/components/widgets-settings/formula/formula.directive.coffee
- src/components/widgets/accounts-custom-calculation/accounts-custom-calculation.directive.coffee
- src/components/widgets/accounts-custom-calculation/accounts-custom-calculation.less
- src/components/widgets/accounts-custom-calculation/accounts-custom-calculation.tmpl.html
- src/filters/moment-date.filter.coffee
- Fixes IE11 incompatibilities
**TODO**
> Release - v1.6.7

- src/components/dashboard-selector/dashboard-selector.directive.coffee
- src/components/widgets-settings/organizations/organizations.directive.coffee
Added ordering to Source: at top of the page and made ordering case agnostic.
> [IMPAC-751] Changed ordering to be case agnostic

- .travis.yml
- bower.json
- karma-min.conf.js
- karma.conf.js
- src/services/dashboards/dashboards.spec.js
- workspace/index.html
- Removes angular scenario as it is breaking jQuery and not used
- Fixes travis chrome launching by using an official travis custom launcher
- Fixes missing dashboard specs for changes from IMPAC-750
> Fix dependency issue, travis chrome launching, & dashboard.svc specs

- src/components/common/duplicate-transactions-list/duplicate-transactions-list.component.coffee
- src/components/common/duplicate-transactions-list/duplicate-transactions-list.less
- src/components/common/duplicate-transactions-list/duplicate-transactions-list.tmpl.html
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
- src/impac-angular.module.js
What has been done:
* Create a new panel "Reconciliation" to list all duple of transactions that has to be reconciliate
* Allow the user Confirm the duplication
*Allow the user Not Confirm (or refuse) the douplication
> [IMAPC-771]: Cashflow Reconciliation Feature

- src/components/common/transactions-add/transactions-add.tmpl.html
On component transaction-add
- Rename Customer to Contact
- Rename Expected payment date to Expected transaction date
> [IMPAC-851]: Rename Customer and Expected payment date

- src/components/common/transactions-list/transactions-list.component.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.directive.coffee
- src/components/widgets/accounts-cash-projection/accounts-cash-projection.tmpl.html
after include recurring transaction for real one
> [IMPAC-768]: BugFix to delete transaction and update transaction list

- src/components/common/transactions-add/transactions-add.component.coffee
- src/components/widgets-layouts/custom/accounts-cash-projection/accounts-cash-projection.directive.coffee
- The save button was not enabled because the contact was not ben loaded
> [IMPAC-887]: BugFix to create recurring transaction for real transaction
